name = "preproc"
uuid = "40e8b810-5cc7-4da3-aaf2-af1af8cbde2c"
authors = ["AgustiÌn Covarrubias <gh@agucova.dev>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
